### ISSUE TITLE
typo on website

### ISSUE THREAD

**Issue by Covid19-badping** [yecdev/ydot#4]
page url: https://y.cash/dev
error near bottom word is mispelled "netword" should be "network"

Full existing text: ycashd

ycashd is the full node implementation that powers the Ycash blockchain and Ycash peer-to-peer netword.

**Comment by hloo** [comment]
Thank you for report this. Fixed by https://github.com/yecdev/ydot/commit/2ee8e996f8eeedc83aeb5230ee6816b872409275.
